etl:
  outputs:
    dev:
      type: duckdb
      path: dbt.duckdb
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: 'us-east-1'
        s3_endpoint: 'localhost:9000'
        s3_use_ssl: 'false'
        s3_url_style: 'path'
        s3_access_key_id: 'minio_access_key'
        s3_secret_access_key: 'minio_secret_key'

  target: dev
